
---
title: "BODY-MEASUREMENT DASHBOARD"
author: "MOHAMMAD KAVISH"
date: "Last updated at `r format(Sys.time())`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
     
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
body_data <- read.csv("E:/R PROGRAMMING/bdims.csv")
```
Column {data-width=650}
-----------------------------------------------------------------------

### Scatter Plot of Age vs. Weight by Sex

```{r}
ggplot(body_data, aes(x = age, y = wgt, color = sex)) +
  geom_point() +
  labs(x = "Age", y = "Weight", color = "Sex")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of Height

```{r}
ggplot(body_data, aes(x = hgt)) +
  geom_histogram(binwidth = 5) +
  labs(x = "Height", y = "Frequency")
```

### Height Distribution by Sex

```{r}
ggplot(body_data, aes(x = sex, y = hgt, fill = factor(sex))) +
  geom_boxplot() +
  labs(x = "Sex", y = "Height")
```

